server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ip_pools?characterEncoding=UTF-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 132.232.103.230
    password: 123456
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  thymeleaf:
    cache: false
